# Docker compose version https://docs.docker.com/compose/compose-file
version: "3.8"

# Docker services
services:
  frontend:
    env_file: .env
    container_name: ${CONTAINER_NAME}
    image: ${IMAGE_NAME}
    build:
      context: Frontend
      dockerfile: Dockerfile
      args:
        CLEAN_YARN_CACHE: "true"
        ENABLE_TYPESCRIPT: ${ENABLE_TYPESCRIPT}
        HOST: ${VUE_UI_HOST}
        PROJECT_PATH: ${PROJECT_PATH}
        NODE_VERSION: ${NODE_VERSION}
    networks:
      local:
        aliases:
          - ${NETWORK}
    ports:
      - ${VUE_UI_PORT}:${VUE_UI_PORT}
      - 8080:8080
    volumes:
      - ./Frontend:${PROJECT_PATH}:consistent
    # Override Dockerfile default command
    command: ["vue", "ui", "--headless", "--port", "${VUE_UI_PORT}", "--host", "${VUE_UI_HOST}"]

  backend:
    build:
      context: Backend
      dockerfile: Dockerfile
    volumes:
      - ./Backend:/var/www/html
    ports:
      - 80:80

# Docker networks
networks:
  local:
    name: ${NETWORK}
